# Generated by Django 4.2.30 on 2026-06-29 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('visit_date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'visitor',
                'indexes': [models.Index(fields=['email'], name='visitor_email_fa9265_idx')],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'province',
                'indexes': [models.Index(fields=['name'], name='province_name_7297bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, to='core.category')),
                ('province', models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.PROTECT, to='core.province')),
            ],
            options={
                'db_table': 'heritage_site',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_name_d601b7_idx'),
        ),
        migrations.AddField(
            model_name='booking',
            name='heritage_site',
            field=models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, to='core.heritagesite'),
        ),
        migrations.AddField(
            model_name='booking',
            name='visitor',
            field=models.ForeignKey(db_column='visitor_id', on_delete=django.db.models.deletion.CASCADE, to='core.visitor'),
        ),
        migrations.AddIndex(
            model_name='heritagesite',
            index=models.Index(fields=['name'], name='heritage_si_name_b69812_idx'),
        ),
        migrations.AddIndex(
            model_name='heritagesite',
            index=models.Index(fields=['province'], name='heritage_si_provinc_ae153b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='heritagesite',
            unique_together={('name', 'province')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['visit_date'], name='booking_visit_d_90abde_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['heritage_site'], name='booking_site_id_6a2a98_idx'),
        ),
    ]
