# Generated by Django 4.2.30 on 2026-09-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='category_name_d601b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='heritagesite',
            name='heritage_si_name_b69812_idx',
        ),
        migrations.RemoveIndex(
            model_name='heritagesite',
            name='heritage_si_provinc_ae153b_idx',
        ),
        migrations.RemoveIndex(
            model_name='province',
            name='province_name_7297bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='visitor_email_fa9265_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_visit_date_idx',
            old_name='booking_visit_d_90abde_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_site_idx',
            old_name='booking_site_id_6a2a98_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='heritage_site',
            field=models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.PROTECT, to='core.heritagesite'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visitor',
            field=models.ForeignKey(db_column='visitor_id', on_delete=django.db.models.deletion.PROTECT, to='core.visitor'),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='booking_date_idx'),
        ),
    ]
